/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:d918a005-6235-425d-9811-b597333aedce",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_J9PAJOlz0",
    "aws_user_pools_web_client_id": "3rcmtfcerga8qn7uhbu67hmvjn",
    "oauth": {
        "domain": "milkylane72259ea7-72259ea7-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "milkylane://signin-callback/",
        "redirectSignOut": "milkylane://signout-callback/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://ypi6dkailngcpheqlte6k3noqq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-bnffwq4ynnfqjmrop653rttoje"
};


export default awsmobile;
